replicaCount: 1

image:
  repository: arunbits/flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 250m

nodeSelector: {}
tolerations: []
affinity: {}
