name: Build, Push, and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "arunbits"
          password: "Progress1980#"

      # Step 4: Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arunbits/flask-app:latest
      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: "AKIA4LAEWBP55EA7E7EZ"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      # Step 6: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      # Step 7: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      # Step 8: Update kubeconfig for EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name flask-iris-cluster

      # Step 9: Deploy using Helm
      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install flask-app ./helm \
            --namespace default \
            --set image.repository=arunbits/flask-app \
            --set image.tag=latest
